---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: swetha254/ganga:dbimage
   ports:
     - "3306:3306"

 application:
   image: swetha254/ganga:appimage
   container_name: appcontainer
   ports:
     - "1323:8080"
   depends_on:
     - "devopsdb"
